img_db/urls.py
#!/usr/bin/python
from django.urls import path
from img_db import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'img_db'
urlpatterns = [
    path('upload/', views.uploadImg, name='upload'),
    path('show/', views.showImg, name='show'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

note/urls.py
#!/usr/bin/python
from django.urls import path
# from django.conf.urls import url
from . import views

app_name = 'note'
urlpatterns = [
    path('admin/', views.index, name='admin'),
    path('', views.index, name='index'),
    path('daily/', views.new_daily, name='daily'),
    path('topics/', views.topics, name='topics'),
    path('entries/', views.entries, name='entries'),
    path('new_topic/', views. new_topic, name='new_topic'),
    path('new_entries/', views.new_entries, name='new_entries'),
    path('edit_entry/<entry_id>', views.edit_entry, name='edit_entry'),

]

notebook/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.views.static import serve
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('note.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('img_db/', include('img_db.urls', namespace='img_db')),
    url(r'^medias/(?P<path>.*)$', serve, {'document_root':
        'C:/Users/LZM/Construction_Daily/static/'}),
    # path('medias/<path>.*', serve, {'document_root':
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
#!/usr/bin/python
from django.urls import path
from . import views
# from django.contrib.auth.views import login 旧版本
from django.contrib.auth.views import LoginView

app_name = 'user'
urlpatterns = [
    # path('login/', login, {'template_name', 'user/login.html'}, name='admin'),
    path('login/', LoginView.as_view(template_name='users/login.html'), name="login"),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register, name='register'),
]

note/models.py
from django.db import models
import django.utils.timezone as timezone
from django.contrib.auth.models import User, Group

# Create your models here.


class Topic(models.Model):
    '''单位工程名称'''
    text = models.CharField(max_length=200,
                            verbose_name='工程名称')
    date_added = models.DateField(default=timezone.now)
    company = models.ForeignKey(Group, on_delete=models.CASCADE,
                                verbose_name='施工单位')
    owner = models.ManyToManyField(User, verbose_name="管理员")
    '''增加单位工程属性'''
    quantity = models.FloatField(default=0, verbose_name='工 程 量')
    character = models.CharField(max_length=255, verbose_name='技术特征')
    start_time = models.DateField(default=timezone.now, verbose_name='开工时间')
    end_time = models.DateField(default=timezone.now, verbose_name='完工时间')
    days = models.IntegerField(default=0, verbose_name='工期(天)')

    class Meta:
        verbose_name = '单位工程'
        verbose_name_plural = '单位工程'

    def __str__(self):
        return self.text


class Entry(models.Model):
    '''施工日报'''
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, verbose_name='工程名称')
    company = models.ForeignKey(Group, on_delete=models.CASCADE, verbose_name='施工单位')
    recorder = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='记录人')
    text = models.TextField(verbose_name='施工日报')
    date_added = models.DateField(default=timezone.now, verbose_name='施工日期')
    '''增加日报细分内容'''
    worker = models.IntegerField(verbose_name='出勤人数')
    footage = models.FloatField(default=0, verbose_name='进尺')
    rock = models.FloatField(default=0, verbose_name='出矸量')
    water = models.FloatField(default=0, verbose_name='排水量')
    cement = models.FloatField(default=0, verbose_name='喷砼')

    class Meta:
        verbose_name = '施工日报'
        verbose_name_plural = '施工日报'

    def __str__(self):
        """返回日报前20字"""
        self.text[:20]
        '''
        if len(self.text) > 20:
            return  + "..."
        else:
            return self.text[:20]
        '''

note/forms.py
#!/usr/bin/python

from django import forms

from . models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text', 'company', 'quantity', 'character',
                  'start_time', 'end_time', 'days']
        labels = {'text': '工程名称'}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = [ 'topic', 'company', 'worker',
                  'footage', 'cement', 'text']
        labels = {'text': '工作内容'}
        widgets = {'text': forms.Textarea(attrs={'cols': 40})}


class EntryForm01(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['company', 'worker', 'footage', 'cement', 'text']
        labels = {'text': '工作内容'}
        widgets = {'text': forms.Textarea(attrs={'cols': 40})}

note/views.py
from django.shortcuts import render
from note.models import Topic, Entry
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from note.forms import TopicForm, EntryForm, EntryForm01
from django.contrib.auth.decorators import login_required
import django.utils.timezone as timezone
from django.contrib.auth.models import User, Group


# Create your views here.
def index(request):
    # 施工日报的主页
    return render(request, 'note/index.html')


@login_required  # 未注册登陆，不允许查看日报
def new_daily(request):
    # 显示（所属单位）或登陆人新填写的施工日报
    user = request.user # 登陆账号人名字
    date_added = timezone.now()  # 查看日报的当前日期

    us = User.objects.get(username=user)
    user_id = us.id  # 登陆人的用户id
    gs = Group.objects.filter(user=user_id) # 登陆人所属群组（区队、部门）
    if gs:                                  # 如果有归属群组
        entries = []
        for group in gs:  # 从数据库查找出当天、所属群组的日报，并排序
            entries += Entry.objects.filter(
        date_added=timezone.localtime().strftime("%F")
        ).filter(company=group).order_by('-date_added').order_by('-id')
        entries = entries
        context = {'entries': entries, 'date_added': date_added}
    else:  # 如果没有归属群组（如新注册，未分组），查找出登陆人当天的记录
        entries = Entry.objects.filter(
        date_added=timezone.localtime().strftime("%F")
        ).filter(recorder=user).order_by('-date_added').order_by('-id')
        context = {'entries': entries, 'date_added': date_added}
    return render(request, 'note/daily.html', context)


@login_required
def topics(request):
    # 显示管理单位的所有工程，如未设定归属单位，显示新建单位工程
    user = request.user  # 登陆人的名字
    date_added = timezone.now()  # 查看工程的当前日期

    us = User.objects.get(username=user)
    user_id = us.id  # 登陆人的用户id
    gs = Group.objects.filter(user=user_id) # 登陆人所属群组
    if gs :
        topics = []
        for group in gs:
            topics += Topic.objects.filter(company=group).order_by('-date_added').order_by('-id')
        context = {'topics': topics}
    else:
        topics = Topic.objects.filter(
        date_added=timezone.localtime().strftime("%F")
        ).order_by('-date_added').order_by('-id')
        context = {'topics': topics}
    return render(request, 'note/topics.html', context)


@login_required
def entries(request):
    # 显示全矿（所管理单位的）施工日报记录15条
    user = request.user  # 登陆人的名字
    us = User.objects.get(username=user)
    user_id = us.id  # 登陆人的用户id
    gs = Group.objects.filter(user=user_id) # 登陆人所属群组
    if gs :
        entries = []
        for group in gs:
            entries += Entry.objects.filter(company=group).order_by('-date_added').order_by('-id')[0:5]
        entries = entries[0:15]
        context = {'entries': entries}
    else:
        entries = Entry.objects.filter(recorder=user).order_by('-date_added').order_by('-id')[0:5]
        context = {'entries': entries}
    return render(request, 'note/entries.html', context)


@login_required
def new_topic(request):
    # 添加单位工程
    user = request.user
    ts = Topic.objects.all()
    if request.method != 'POST':
        # 未提交数据：创建一个新表单
        form = TopicForm()
        #print("单位工程不能重复!")
    else:
        # POST提交的数据，对数据进行处理
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            text = new_topic.text
            for i in ts:
                if text == i.text:
                    # 如工程重复，清空重新填写
                    return HttpResponseRedirect(reverse('note:new_topic'))
            new_topic.save()
            return HttpResponseRedirect(reverse('note:topics'))
    context = {'form': form}
    return render(request, 'note/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
    '''在指定单位工程中添加施工日报'''
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        # 未提交数据，创建一个空表单
        form = EntryForm01()
    else:
        # post提交的数据，对数据进行处理
        form = EntryForm01(data=request.POST)
        # 判断单位工程是否填写重复！
        es = Entry.objects.filter(
            date_added=timezone.now().strftime("%F"))
        if form.is_valid:
            new_entry = form.save(commit=False)
            for i in es:
                if topic == i.topic:
                    # 如工程重复，清空重新填写
                    return HttpResponseRedirect(reverse(
                            'note:new_entry', args=[topic_id]))
            new_entry.topic = topic
            new_entry.recorder = request.user
            new_entry.save()
            return HttpResponseRedirect(reverse('note:topic', args=[topic_id]))
    context = {'topic': topic, 'form': form}
    return render(request, 'note/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    '''编辑施工日报'''
    recorder = request.user
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    # 确认请求的日报当前用户记录
    if entry.owner != request.user:
        raise Http404
    if request.method != 'POST':
        # 初次请求，使用当前日报填充表单
        form = EntryForm01(instance=entry)
    else:
        # post提交的数据，对数据进行处理
        form = EntryForm01(request.POST)
        if form.is_valid:
            entry = form.save(commit=False)
            entry.recorder = recorder
            entry.id = entry_id
            entry.topic = topic
            entry.save()
            return HttpResponseRedirect(reverse('note:daily'))
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'note/edit_entry.html', context)


@login_required
def new_entries(request):
    '''选择单位工程，添加施工日报'''
    date_added = timezone.now()
    recorder = request.user
    if request.method != 'POST':
        # 未提交数据，创建一个空表单
        form = EntryForm()
    else:
        # post提交的数据，对数据进行处理
        form = EntryForm(data=request.POST)
        # 判断单位工程是否填写重复！
        es = Entry.objects.filter(
            date_added=timezone.localtime().strftime("%F"))
        if form.is_valid:
            new_entry = form.save(commit=False)
            topic = new_entry.topic
            for i in es:
                if topic == i.topic:
                    # 如工程重复，清空重新填写
                    return HttpResponseRedirect(reverse('note:new_entries'))
            new_entry.recorder = recorder
            new_entry.date_added = date_added
            new_entry.save()
            form.save()
            return HttpResponseRedirect(reverse('note:daily'))
    context = {'form': form}
    return render(request, 'note/new_entries.html', context)

note/templates/note/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="zh-cn">
    <head>
        <meta charset="utf-8">
 <meta > 

 <meta name="viewport" content="width=device-width, initial-scale=1"> 

        <title>施工日报</title>

        {% bootstrap_css %}
        {% bootstrap_javascript %}
    </head>
<body>
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top"> 
    
    <div class="container"> 
        <div class="navbar-header">       
            <button type="button" class="navbar-toggle collapsed"   data-toggle="collapse"
data-target="#navbar" 
           aria-expanded="false" aria-controls="navbar"> 
           </button>
            <a class="navbar-brand" href="{% url 'note:new_entries' %}"> 填写日报</a> <a class="navbar-brand" href="{% url 'note:admin' %}"> 管理日报</a><a class="navbar-brand" href="{% url 'img_db:show' %}"> 工程图片</a>
         </div>
                   
        <div id="navbar" class="navbar-collapse collapse">  
          <ul class="nav navbar-nav">
            <li><a href=" {% url 'note:topics' %}"> 单位工程 </a></li>
             <li><a href=" {% url 'note:entries' %}"> 施工记录 </a></li>
             <li><a href=" {% url 'img_db:upload' %}"> 图片上传 </a></li>
            </ul>
            
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li>你好！{{ user.username }}</li>
                <li><a href="{% url 'users:logout' %}">注销
                      </a></li>
                {% else %}
                <li><a href="{% url 'users:register' %}">请注册
                       </a></li>
                  <li><a href="{% url 'users:login' %}">请登录
                        </a></li>
                  {% endif %}
                </ul>
            </div> <!--/.nav-collapse -->     
    </div> 

</nav>

<div class="container">

 <div class="page-header">
     {% block header %}{% endblock header %}

 </div> 

 <div>

    {% block content %}{% endblock content %} 

 </div> 

 </div> <!-- /container -->


    <div class="container theme-showcase" role="main">
      <div class="page-header">
      </div>
      <footer class="footer">
        <p>&copy;版权自由，欢迎使用！ <a href="mailto:3357025409@qq.com">反馈：地层深处</a>&emsp;2020年3月</p>
      </footer>
    </div> <!-- /container -->

note/templates/note/daily.html
{% extends "note/base.html" %}

{% load bootstrap3 %}
 {% block header %}
<a href=" {% url 'note:new_entries' %}"><h2>施工日报</h2></a>
{% endblock header %} 

{% block content %}

     <!--施工记录表单-->
    <div class="row" >
      <div class="col-md-10" style="width: 1080px;">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>序号</th>
              <!--<th>日期</th>-->
              <th><a href=" {% url 'note:topics' %}"> 单位工程 </a></th>
              <th>施工单位</th>
              <th>出勤</th>
              <th>进尺</th>         
              <th>喷砼</th>         
              <th>日报内容</th>             
            </tr>
          </thead>
          <tbody>
        {% for entry in entries %}
        <tr>
          <td>{{ entry.id }}</td>
          <!--<td>{{entry.date_added|date:'Y-m-d'}}</td>-->
          <td><a href="{% url 'note:edit_entry' entry.id %}">{{entry.topic}}</a></td>
          <td>{{ entry.company }}</td>
          <td>{{ entry.worker }}</td>
          <td>{{ entry.footage }}</td>
          <td>{{ entry.cement }}</td>
          <td>{{entry.text|truncatechars:70}}</td>
          
        </tr>   
          </tbody>
        {% empty %}              
        <a href=" {% url 'note:new_entries' %}">请填写日报</a>
         {% endfor %}
        </table> 
<p align="right">&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;记录：{{ user }}&emsp;日期：{{date_added}}</p>
      </div>   
    </div>

{% endblock content %}

note/templates/note/edit_entry.html
{% extends "note/base.html" %}
{% load bootstrap3 %}   
 
{% block header %}
<h2>
    修改{{ topic }}</a>日报:
</h2>
{% endblock header %}

{% block content %}

<form action="{% url 'note:edit_entry' entry.id %}" method='post'
 class="form"> 
 {% csrf_token %}
{% bootstrap_form form %} 
 
{% buttons %} 
 <button name="submit" class="btn btn-primary">保存修改</button> 
 {% endbuttons %} 

 </form> 

 {% endblock content %} 

note/templates/note/entries.html
{% extends "note/base.html" %}
{% load bootstrap3 %}
{% block header %}
<h2>施工记录</h2>
{% endblock header %} 
{% block content %}
     <!--施工记录表单-->
    <div class="row" >
      <div class="col-md-9" style="width: 1080px;">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>序号</th>
              <th>日期</th>
              <th>单位工程</th>
              <th>施工单位</th>
              <th>出勤</th>
              <th>进尺（m）</th>             
              <th>喷砼</th>             
              <th>日报内容</th>
              <th>记录员</th>
            </tr>
          </thead>
          <tbody>
        {% for entry in entries %}
        <tr>
          <td>{{ entry.id }}</td>
          <td>{{entry.date_added|date:'Y-m-d'}}</td>
          <td>{{entry.topic}}</td>
          <td>{{ entry.company }}</td>
          <td>{{ entry.worker }}</td>
          <td>{{ entry.footage }}</td>
          <td>{{ entry.cement }}</td>
          <td>{{entry.text|truncatechars:100}}</td>
          <td>{{ entry.recorder }}</td>
        </tr>   
          </tbody>
        {% empty %}              
         <a href=" {% url 'note:new_entries' %}">请填写日报</a>
        {% endfor %}
        </table>        
      </div>   
    </div>
{% endblock content %}

note/templates/note/index.html
{% extends "note/base.html" %}
{% load static %}
{% load bootstrap3 %}
<html>
{% block header %}
 <h3 align="center">请于08:00前<a href="{% url 'note:new_entries' %}">提交日报</a></h3>
 测试账号：用户名：dhz 密码：dhz12345
{% endblock header %}

{% block content %}
<body>
<div align="center" class='jumbotron'>
 <h3>大海则煤矿</h3> <a href="{% url 'note:daily' %}"><h1>施工日报</h1> </a>
</div> 
<div align="left" style="line-height:30px">
    &emsp;&emsp;日报按单位工程进行填写，要求准确填写每天的出勤和工程进度。    
    对主要工作内容进行描述，对存在的问题和影响情况进行详细描述。
    对当天的工程计划、工作安排、主要沟通和协调事项进行登记上报。
    日报填写需要注册，日报管理需要向管理员申请权限。注册后会对填报的内容和数据进行上传和保护。
    你可以随时登录网站，对日报内容进行查看，了解工程施工进展情况。
    <a href="{% url 'img_db:upload' %}">图片上传</a>
</div>
   <div class="navbar-collapse collapse"> 
    <img src="{% static "1.jpg" %}" alt="" height=200 width=340 />
    <img src="{% static "2.jpg" %}" alt="煤矿规划图" height=200 width=340 />
    <img src="{% static "3.jpg" %}" alt="" height=200 width=340 />
   </div>
 </body>
</html>
{% endblock content %}

note/templates/note/new_entries.html
	{% extends "note/base.html" %}
{% load bootstrap3 %}   
 
{% block header %}
  <h2><a href="{% url 'note:daily' %}">施工日报</a></h2>
{% endblock header %}

{% block content %}

<form action="{% url 'note:new_entries' %}" method='post'
 class="form"> 
 {% csrf_token %}
{% bootstrap_form form %} 
 
{% buttons %} 
 <button name="submit" class="btn btn-primary">提交日报</button> 
 {% endbuttons %} 

 </form> 

 {% endblock content %} 

note/templates/note/new_entry.html
{% extends "note/base.html" %}
{% load bootstrap3 %}   
 
{% block header %}
  <h2>{{ topic }}施工日报</h2>
{% endblock header %}

{% block content %}

<form action="{% url 'note:new_entry' topic.id %}" method='post'
 class="form"> 
 {% csrf_token %}
{% bootstrap_form form %} 
 
{% buttons %} 
 <button name="submit" class="btn btn-primary">提交日报</button> 
 {% endbuttons %} 

 </form> 

 {% endblock content %} 

note/templates/note/new_topic.html
{% extends "note/base.html" %}

{% load bootstrap3 %} 
{% block header %}
 <h2>新增单位工程</h2> 
{% endblock header %}

{% block content %}
 
<form action="{% url 'note:new_topic' %}" method='post'
 class="form"> 
 {% csrf_token %}
{% bootstrap_form form %} 
 
{% buttons %} 
 <button name="submit" class="btn btn-primary">提交保存</button> 
 {% endbuttons %} 
 </form> 

{% endblock content %}

note/templates/note/topic.html
{% extends "note/base.html" %}

{% load bootstrap3 %}
{% block header %}
<h2>  
<a href="{% url 'note:new_entry' topic.id %}">写{{ topic }}日报</a> 
</h2>
{% endblock header %}
{% block content %}

    <!--施工记录表单-->
    <div class="row" >
      <div class="col-md-8" style="width: 780px;">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>序号</th>
              <th>日期</th>
              <th>施工单位</th>
              <th>出勤人数</th>
              <th>进尺（m）</th>         
              <th>水泥/砼量</th>         
              <th>日报内容</th>
            </tr>
          </thead>
          <tbody>
        {% for entry in entries %}
        <tr>
          <td>{{ entry.id }}</td>
          <td>{{entry.date_added|date:'Y-m-d'}}</td>
          <td>{{ entry.company }}</td>
          <td>{{ entry.worker }}</td>
          <td>{{ entry.footage }}</td>
          <td>{{ entry.cement }}</td>
          <td>{{entry.text|linebreaks}}</td>
          <!--<td><a href="{% url 'note:edit_entry' entry.id %}">修改</a></td>-->
        </tr>   
          </tbody>
        {% empty %}              
         写日报
        {% endfor %}
        </table>        
      </div>   
    </div>      
{% endblock content %}

note/templates/note/topics.html
{% extends "note/base.html" %}
{% load bootstrap3 %}
{% block header %}
 <h3><a href="{% url 'note:new_topic' %}">增加单位工程</a></h3>
{% endblock header %}
{% block content %}
    <!--单位工程表单-->
    <div class="row" >
      <div class="col-md-8" style="width: 780px;">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>序号</th>
              <th>工程名称</th>
              <th>施工单位</th>
              <th>工程量</th>
              <th>技术特征</th>
              <th>开工时间</th>
              <th>完工时间</th>
              <th>工期（天）</th>          
            </tr>
          </thead>
          <tbody>
        {% for topic in topics %}
        <tr>
          <td>{{ topic.id }}</td>
          <td>{{ topic.text }}</a></td>
          <td>{{ topic.company }}</a></td>
          <td>{{ topic.quantity }}</td>
          <td>{{ topic.character }}</td>
          <td>{{topic.start_time|date:'Y-m-d'}}</td>
          <td>{{topic.end_time|date:'Y-m-d'}}</td>
          <td>{{ topic.days }}</td>
        </tr>   
          </tbody>
        {% empty %}              
         <a href="{% url 'note:new_topic' %}">请增加单位工程</a>
        {% endfor %}
        </table>        
      </div>   
    </div>    
{% endblock content %}